import { DatabaseStore, User, Profile, Portfolio, Position, Trade, TradeJournal, RiskAlert, BehavioralSignal, MarketData } from './database';

export function getInitialSeedData(): DatabaseStore {
  const now = new Date();
  
  // Helper for relative timestamps in ISO string
  const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600 * 1000).toISOString();
  const daysAgo = (d: number) => new Date(now.getTime() - d * 86400 * 1000).toISOString();
  const minsAgo = (m: number) => new Date(now.getTime() - m * 60 * 1000).toISOString();

  // 1. Primary Demo User & Profile
  const user: User = {
    id: 'user_demo_01',
    email: 'utkarsh@tradeguard.io',
    fullName: 'Utkarsh',
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  };

  const profile: Profile = {
    id: 'prof_demo_01',
    userId: user.id,
    riskTolerance: 'moderate',
    maxAccountRiskPct: 2.0, // 2% max account risk
    maxDrawdownLimitPct: 10.0,
    preferredCurrency: '₹',
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  };

  // 2. Portfolio
  const portfolio: Portfolio = {
    id: 'port_demo_01',
    userId: user.id,
    name: "Utkarsh's Portfolio",
    totalBalance: 100000.0, // ₹1,00,000 starting capital
    availableCash: 64200.0,
    allocatedMargin: 35800.0,
    dailyPnl: -1420.0,
    realizedPnl: -3850.0,
    peakBalance: 112500.0,
    maxDrawdownPct: 8.5,
    createdAt: daysAgo(30),
    updatedAt: hoursAgo(1),
  };

  // 3. Market Data (Realistic Market Prices)
  const marketData: Record<string, MarketData> = {
    'RELIANCE': { symbol: 'RELIANCE', name: 'Reliance Industries', assetClass: 'EQUITY', currentPrice: 2950.0, dayChangePct: 1.2, high24h: 2980.0, low24h: 2920.0, volume24h: 4200000, updatedAt: minsAgo(2) },
    'TATASTEEL': { symbol: 'TATASTEEL', name: 'Tata Steel Ltd', assetClass: 'EQUITY', currentPrice: 155.0, dayChangePct: -2.4, high24h: 160.0, low24h: 153.5, volume24h: 8900000, updatedAt: minsAgo(2) },
    'INFY': { symbol: 'INFY', name: 'Infosys Ltd', assetClass: 'EQUITY', currentPrice: 1820.0, dayChangePct: -0.8, high24h: 1845.0, low24h: 1810.0, volume24h: 3100000, updatedAt: minsAgo(2) },
    'NVDA': { symbol: 'NVDA', name: 'NVIDIA Corp', assetClass: 'EQUITY', currentPrice: 128.5, dayChangePct: 3.4, high24h: 130.0, low24h: 124.0, volume24h: 45000000, updatedAt: minsAgo(2) },
    'BTC/USD': { symbol: 'BTC/USD', name: 'Bitcoin / US Dollar', assetClass: 'CRYPTO', currentPrice: 64200.0, dayChangePct: -1.8, high24h: 65800.0, low24h: 63900.0, volume24h: 1820000000, updatedAt: minsAgo(2) },
  };

  // 4. Open Positions (Active Positions)
  const positions: Position[] = [
    {
      id: 'pos_01',
      portfolioId: portfolio.id,
      symbol: 'RELIANCE',
      assetClass: 'EQUITY',
      direction: 'LONG',
      quantity: 50,
      entryPrice: 2920.0, // Exposure: ₹1,46,000 (with leverage 5x)
      currentPrice: 2950.0,
      stopLoss: 2840.0, // Risk per unit = ₹80 * 50 = ₹4,000 (4.0% of portfolio) -> ABOVE 2% LIMIT!
      takeProfit: 3100.0,
      leverage: 5,
      unrealizedPnl: 1500.0,
      unrealizedPnlPct: 1.03,
      riskScore: 72, // HIGH RISK due to position size 1.46x portfolio & SL risk
      openedAt: hoursAgo(4),
      updatedAt: minsAgo(5),
    },
    {
      id: 'pos_02',
      portfolioId: portfolio.id,
      symbol: 'TATASTEEL',
      assetClass: 'EQUITY',
      direction: 'LONG',
      quantity: 200,
      entryPrice: 158.0,
      currentPrice: 155.0,
      stopLoss: 149.0, // Risk per unit = ₹9 * 200 = ₹1,800 (1.8% of portfolio)
      takeProfit: 172.0,
      leverage: 1,
      unrealizedPnl: -600.0,
      unrealizedPnlPct: -1.90,
      riskScore: 45,
      openedAt: hoursAgo(18),
      updatedAt: minsAgo(5),
    }
  ];

  // 5. Realistic Seeded Historical Trades
  const trades: Trade[] = [
    {
      id: 'tr_01',
      portfolioId: portfolio.id,
      symbol: 'RELIANCE',
      assetClass: 'EQUITY',
      direction: 'LONG',
      quantity: 25,
      entryPrice: 2750.0,
      exitPrice: 2820.0,
      stopLoss: 2710.0,
      takeProfit: 2850.0,
      leverage: 1,
      pnl: 1750.0,
      pnlPct: 2.54,
      status: 'CLOSED',
      riskScoreAtEntry: 32,
      executedAt: daysAgo(28),
      closedAt: daysAgo(26),
    },
    {
      id: 'tr_02',
      portfolioId: portfolio.id,
      symbol: 'INFY',
      assetClass: 'EQUITY',
      direction: 'LONG',
      quantity: 30,
      entryPrice: 1650.0,
      exitPrice: 1710.0,
      stopLoss: 1610.0,
      takeProfit: 1720.0,
      leverage: 1,
      pnl: 1800.0,
      pnlPct: 3.63,
      status: 'CLOSED',
      riskScoreAtEntry: 28,
      executedAt: daysAgo(25),
      closedAt: daysAgo(23),
    },
    {
      id: 'tr_03',
      portfolioId: portfolio.id,
      symbol: 'TATASTEEL',
      assetClass: 'EQUITY',
      direction: 'SHORT',
      quantity: 150,
      entryPrice: 145.0,
      exitPrice: 141.0,
      stopLoss: 148.0,
      takeProfit: 138.0,
      leverage: 1,
      pnl: 600.0,
      pnlPct: 2.75,
      status: 'CLOSED',
      riskScoreAtEntry: 35,
      executedAt: daysAgo(22),
      closedAt: daysAgo(21),
    },
    {
      id: 'tr_04',
      portfolioId: portfolio.id,
      symbol: 'RELIANCE',
      assetClass: 'EQUITY',
      direction: 'LONG',
      quantity: 20,
      entryPrice: 2800.0,
      exitPrice: 2760.0,
      stopLoss: 2750.0,
      takeProfit: 2900.0,
      leverage: 1,
      pnl: -800.0,
      pnlPct: -1.42,
      status: 'CLOSED',
      riskScoreAtEntry: 30,
      executedAt: daysAgo(20),
      closedAt: daysAgo(19),
    },
    {
      id: 'tr_05',
      portfolioId: portfolio.id,
      symbol: 'NVDA',
      assetClass: 'EQUITY',
      direction: 'LONG',
      quantity: 15,
      entryPrice: 110.0,
      exitPrice: 118.0,
      stopLoss: 106.0,
      takeProfit: 120.0,
      leverage: 2,
      pnl: 120.0,
      pnlPct: 7.27,
      status: 'CLOSED',
      riskScoreAtEntry: 42,
      executedAt: daysAgo(18),
      closedAt: daysAgo(16),
    },
    {
      id: 'tr_06',
      portfolioId: portfolio.id,
      symbol: 'BTC/USD',
      assetClass: 'CRYPTO',
      direction: 'LONG',
      quantity: 0.1,
      entryPrice: 61000.0,
      exitPrice: 63500.0,
      stopLoss: 59500.0,
      takeProfit: 64000.0,
      leverage: 3,
      pnl: 250.0,
      pnlPct: 4.10,
      status: 'CLOSED',
      riskScoreAtEntry: 48,
      executedAt: daysAgo(15),
      closedAt: daysAgo(14),
    },
    {
      id: 'tr_07',
      portfolioId: portfolio.id,
      symbol: 'INFY',
      assetClass: 'EQUITY',
      direction: 'LONG',
      quantity: 25,
      entryPrice: 1720.0,
      exitPrice: 1765.0,
      stopLoss: 1690.0,
      takeProfit: 1780.0,
      leverage: 1,
      pnl: 1125.0,
      pnlPct: 2.61,
      status: 'CLOSED',
      riskScoreAtEntry: 31,
      executedAt: daysAgo(13),
      closedAt: daysAgo(12),
    },
    {
      id: 'tr_08',
      portfolioId: portfolio.id,
      symbol: 'RELIANCE',
      assetClass: 'EQUITY',
      direction: 'LONG',
      quantity: 25,
      entryPrice: 2840.0,
      exitPrice: 2890.0,
      stopLoss: 2800.0,
      takeProfit: 2920.0,
      leverage: 1,
      pnl: 1250.0,
      pnlPct: 1.76,
      status: 'CLOSED',
      riskScoreAtEntry: 33,
      executedAt: daysAgo(11),
      closedAt: daysAgo(10),
    },
    {
      id: 'tr_09',
      portfolioId: portfolio.id,
      symbol: 'TATASTEEL',
      assetClass: 'EQUITY',
      direction: 'LONG',
      quantity: 200,
      entryPrice: 150.0,
      exitPrice: 156.0,
      stopLoss: 145.0,
      takeProfit: 160.0,
      leverage: 1,
      pnl: 1200.0,
      pnlPct: 4.00,
      status: 'CLOSED',
      riskScoreAtEntry: 34,
      executedAt: daysAgo(9),
      closedAt: daysAgo(8),
    },
    {
      id: 'tr_10',
      portfolioId: portfolio.id,
      symbol: 'NVDA',
      assetClass: 'EQUITY',
      direction: 'LONG',
      quantity: 20,
      entryPrice: 120.0,
      exitPrice: 116.0,
      stopLoss: 115.0,
      takeProfit: 128.0,
      leverage: 2,
      pnl: -80.0,
      pnlPct: -3.33,
      status: 'CLOSED',
      riskScoreAtEntry: 45,
      executedAt: daysAgo(7),
      closedAt: daysAgo(6),
    },
    {
      id: 'tr_11',
      portfolioId: portfolio.id,
      symbol: 'INFY',
      assetClass: 'EQUITY',
      direction: 'LONG',
      quantity: 30,
      entryPrice: 1780.0,
      exitPrice: 1810.0,
      stopLoss: 1740.0,
      takeProfit: 1830.0,
      leverage: 1,
      pnl: 900.0,
      pnlPct: 1.68,
      status: 'CLOSED',
      riskScoreAtEntry: 36,
      executedAt: daysAgo(6),
      closedAt: daysAgo(5),
    },
    {
      id: 'tr_12',
      portfolioId: portfolio.id,
      symbol: 'RELIANCE',
      assetClass: 'EQUITY',
      direction: 'SHORT',
      quantity: 25,
      entryPrice: 2920.0,
      exitPrice: 2870.0,
      stopLoss: 2950.0,
      takeProfit: 2850.0,
      leverage: 1,
      pnl: 1250.0,
      pnlPct: 1.71,
      status: 'CLOSED',
      riskScoreAtEntry: 38,
      executedAt: daysAgo(5),
      closedAt: daysAgo(4),
    },
    {
      id: 'tr_13_loss1',
      portfolioId: portfolio.id,
      symbol: 'RELIANCE',
      assetClass: 'EQUITY',
      direction: 'LONG',
      quantity: 25,
      entryPrice: 2940.0,
      exitPrice: 2890.0,
      stopLoss: 2890.0,
      takeProfit: 3020.0,
      leverage: 2,
      pnl: -1250.0,
      pnlPct: -1.70,
      status: 'CLOSED',
      riskScoreAtEntry: 45,
      executedAt: daysAgo(3),
      closedAt: daysAgo(3),
    },
    {
      id: 'tr_14_loss2',
      portfolioId: portfolio.id,
      symbol: 'NVDA',
      assetClass: 'EQUITY',
      direction: 'LONG',
      quantity: 25,
      entryPrice: 126.0,
      exitPrice: 121.5,
      stopLoss: 121.5,
      takeProfit: 133.0,
      leverage: 3,
      pnl: -112.5,
      pnlPct: -3.57,
      status: 'CLOSED',
      riskScoreAtEntry: 55,
      executedAt: hoursAgo(48),
      closedAt: hoursAgo(46),
    },
    {
      id: 'tr_15_loss3',
      portfolioId: portfolio.id,
      symbol: 'TATASTEEL',
      assetClass: 'EQUITY',
      direction: 'LONG',
      quantity: 300,
      entryPrice: 160.0,
      exitPrice: 154.0,
      stopLoss: 154.0,
      takeProfit: 168.0,
      leverage: 2,
      pnl: -1800.0,
      pnlPct: -3.75,
      status: 'CLOSED',
      riskScoreAtEntry: 62,
      executedAt: hoursAgo(30),
      closedAt: hoursAgo(28),
    },
    {
      id: 'tr_16_revenge',
      portfolioId: portfolio.id,
      symbol: 'RELIANCE',
      assetClass: 'EQUITY',
      direction: 'LONG',
      quantity: 75,
      entryPrice: 2910.0,
      exitPrice: 2870.0,
      stopLoss: 2850.0,
      takeProfit: 3000.0,
      leverage: 4,
      pnl: -3000.0,
      pnlPct: -1.37,
      status: 'CLOSED',
      riskScoreAtEntry: 88,
      executedAt: hoursAgo(27),
      closedAt: hoursAgo(24),
    },
    {
      id: 'tr_17_fomo',
      portfolioId: portfolio.id,
      symbol: 'BTC/USD',
      assetClass: 'CRYPTO',
      direction: 'LONG',
      quantity: 0.35,
      entryPrice: 65800.0,
      exitPrice: 64200.0,
      stopLoss: 63800.0,
      takeProfit: 68000.0,
      leverage: 5,
      pnl: -560.0,
      pnlPct: -2.43,
      status: 'CLOSED',
      riskScoreAtEntry: 82,
      executedAt: hoursAgo(20),
      closedAt: hoursAgo(15),
    },
    {
      id: 'tr_18',
      portfolioId: portfolio.id,
      symbol: 'INFY',
      assetClass: 'EQUITY',
      direction: 'LONG',
      quantity: 30,
      entryPrice: 1800.0,
      exitPrice: 1825.0,
      stopLoss: 1770.0,
      takeProfit: 1850.0,
      leverage: 1,
      pnl: 750.0,
      pnlPct: 1.38,
      status: 'CLOSED',
      riskScoreAtEntry: 38,
      executedAt: hoursAgo(12),
      closedAt: hoursAgo(8),
    }
  ];

  // 6. Trade Journals
  const journals: TradeJournal[] = [
    {
      id: 'j_01',
      tradeId: 'tr_16_revenge',
      userId: user.id,
      notes: 'Felt frustrated after 3 losses in a row. Scaled up position size aggressively hoping to recover lost capital.',
      emotionalState: 'REVENGE',
      convictionLevel: 2,
      tags: ['POST_LOSS_SPIKE', 'OVERSIZED', 'REVENGE'],
      createdAt: hoursAgo(27),
    },
    {
      id: 'j_02',
      tradeId: 'tr_17_fomo',
      userId: user.id,
      notes: 'BTC was surging past $65.8k on Twitter hype. Jumped in near daily high without waiting for pullback.',
      emotionalState: 'FOMO',
      convictionLevel: 3,
      tags: ['HIGH_ENTRY', 'FOMO_CHASE'],
      createdAt: hoursAgo(20),
    },
    {
      id: 'j_03',
      tradeId: 'tr_18',
      userId: user.id,
      notes: 'Stuck strictly to 1% risk rule on INFY. Calm execution at support.',
      emotionalState: 'CALM',
      convictionLevel: 4,
      tags: ['DISCIPLINED', 'SUPPORT_BOUNCE'],
      createdAt: hoursAgo(12),
    }
  ];

  // 7. Active Risk Alerts
  const riskAlerts: RiskAlert[] = [
    {
      id: 'alert_01',
      portfolioId: portfolio.id,
      positionId: 'pos_01',
      severity: 'DANGER',
      category: 'POSITION_SIZE',
      title: 'Position Size Exceeds Portfolio Limit',
      explanation: 'Your open RELIANCE position of 50 units represents ₹1,46,000 exposure (146% of total portfolio capital with 5x leverage).',
      whyItMatters: 'A 2.7% adverse move in RELIANCE will wipe out 4.0% of total account capital, breaching your max 2.0% risk rule.',
      suggestedAction: 'Reduce position quantity from 50 to 25 units using the Loss Shield to align with risk tolerance.',
      isDismissed: false,
      createdAt: hoursAgo(3),
    },
    {
      id: 'alert_02',
      portfolioId: portfolio.id,
      severity: 'WARNING',
      category: 'REVENGE_RISK',
      title: 'Post-Loss Size Escalation Detected',
      explanation: 'After 3 consecutive losses totaling -₹4,175, your recent average position size spiked by 185%.',
      whyItMatters: 'Trading larger sizes immediately following drawdown periods historically correlates with a 72% loss probability.',
      suggestedAction: 'Enforce a 2-hour cooling period after consecutive loss trades before opening new orders.',
      isDismissed: false,
      createdAt: hoursAgo(10),
    },
    {
      id: 'alert_03',
      portfolioId: portfolio.id,
      severity: 'INFO',
      category: 'DRAWDOWN',
      title: 'Portfolio Drawdown at 8.5%',
      explanation: 'Current portfolio balance (₹96,150) is 8.5% below historical peak (₹1,12,500).',
      whyItMatters: 'Approaching the 10.0% maximum drawdown ceiling specified in your risk profile.',
      suggestedAction: 'Lower leverage on new entries to maximum 2x until drawdown recovers below 5.0%.',
      isDismissed: false,
      createdAt: hoursAgo(18),
    }
  ];

  // 8. Calculated Behavioral Signals
  const behavioralSignals: BehavioralSignal = {
    id: 'bs_demo_01',
    userId: user.id,
    revengeScore: 78,
    fomoScore: 64,
    overtradingScore: 42,
    riskEscalationScore: 82,
    positionAnomalyScore: 75,
    primaryArchetype: 'Drawdown Escalator',
    dominantTrigger: 'Size escalation immediately following consecutive loss trades',
    calculatedAt: hoursAgo(1),
  };

  return {
    user,
    profile,
    portfolio,
    positions,
    trades,
    journals,
    riskAlerts,
    behavioralSignals,
    marketData,
  };
}
